---
driver:
  name: vagrant

driver_config:
  box_download_insecure: true
  http_proxy: <%= ENV['http_proxy'] %>
  https_proxy: <%= ENV['http_proxy'] %>
  no_proxy: <%= ENV['no_proxy'] %>
  network:
          - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
          - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]

provisioner:
  name: chef_zero
  client_rb:
    http_proxy: <%= ENV['http_proxy'] %>
    https_proxy: <%= ENV['http_proxy'] %>
    no_proxy: <%= ENV['no_proxy'] %>
    no_lazy_load: true

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04


suites:
  - name: default
    run_list:
      - recipe[svops_docker::default]
    attributes:

verifier:
  name: inspec
